"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.coinexAdaptor = exports.ftxSocketAdaptor = exports.ftxAdaptor = exports.coinbaseSocketAdaptor = exports.coinbaseAdaptor = exports.binanceSocketAdaptor = exports.binanceAdaptor = void 0;
var binanceAdaptor_1 = require("./binanceAdaptor");
var ftxAdaptor_1 = require("./ftxAdaptor");
var coinbaseAdaptor_1 = require("./coinbaseAdaptor");
var coinexAdaptor_1 = require("./coinexAdaptor");
exports.binanceAdaptor = binanceAdaptor_1.candleAdaptor;
exports.binanceSocketAdaptor = binanceAdaptor_1.socketAdaptor;
exports.coinbaseAdaptor = coinbaseAdaptor_1.candleAdaptor;
exports.coinbaseSocketAdaptor = coinbaseAdaptor_1.socketAdaptor;
exports.ftxAdaptor = ftxAdaptor_1.candleAdaptor;
exports.ftxSocketAdaptor = ftxAdaptor_1.socketAdaptor;
exports.coinexAdaptor = coinexAdaptor_1.candleAdaptor;
